# Generated by Django 5.1.1 on 2024-09-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='housewise.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='housewise.usertype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
