# Generated by Django 5.1.1 on 2024-10-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0003_housetype_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CR',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cr_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('house_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='housewise.housetype')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
                ('feedback_description', models.TextField()),
                ('feedback_datetime', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='housewise.project')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_description', models.TextField()),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='housewise.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('materials_id', models.AutoField(primary_key=True, serialize=False)),
                ('materials_name', models.CharField(max_length=100)),
                ('house_type', models.ManyToManyField(related_name='materials', to='housewise.housetype')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='housewise.materials')),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('roof_id', models.AutoField(primary_key=True, serialize=False)),
                ('roof_type', models.CharField(choices=[('colored_roof', 'Colored Roof'), ('plain_roof', 'Plain Roof')], max_length=20)),
                ('trusses', models.CharField(blank=True, choices=[('metal_trusses', 'Metal Trusses'), ('wooden_trusses', 'Wooden Trusses')], max_length=20)),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roofs', to='housewise.housetype')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('room_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='housewise.housetype')),
            ],
        ),
    ]
