# Generated by Django 5.1.1 on 2024-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0004_cr_feedback_feedbackcomment_materials_materialprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='house_type',
            field=models.ManyToManyField(blank=True, related_name='materials', to='housewise.housetype'),
        ),
    ]
