# Generated by Django 5.1.1 on 2024-10-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0005_alter_materials_house_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cr',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='roof',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='house_type',
        ),
        migrations.AddField(
            model_name='cr',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='housewise.project'),
        ),
        migrations.AddField(
            model_name='materials',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='materials', to='housewise.project'),
        ),
        migrations.AddField(
            model_name='roof',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roofs', to='housewise.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='housewise.project'),
            preserve_default=False,
        ),
    ]
