# Generated by Django 5.1.1 on 2024-11-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0006_remove_cr_house_type_remove_materials_house_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhousewise',
            old_name='user_id',
            new_name='id',
        ),
    ]
